# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
env:
  BUILD_CONFIGURATION: Release
  NUPKG_OUTPUT: nupkgs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c ${{ env.BUILD_CONFIGURATION }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
 
  publish-to-nuget:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pack
      run: dotnet pack -c ${{ env.BUILD_CONFIGURATION }} -o ${{ env.NUPKG_OUTPUT }}
    - name: Push
      run: dotnet nuget push --api-key ${{ secrets.NUGET_TOKEN }} -s "https://api.nuget.org/v3/index.json" "~/nupkgs/*.nupkg"
